title: Genealogist
email: genealogist@d9beud.com
description: >-
  Uncover the secrets of your past with Genealogist. Our intuitive genealogy 
  tool allows you to create, explore, and share your family tree with ease. 
  Discover your family history like never before. Unlock your roots today 
  with Genealogist.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://genealogist.d9beud.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
app_url: "https://app.genealogist.d9beud.com"

# Build settings
plugins:
  - jekyll-feed

sass:
  style: compressed
  sourcemap: development

exclude:
  - _assets/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json